version:  "3.7"

services:
  mlapp:
    container_name: drugclassification
    image: hossamrizk/drugclassification
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile